### ISSUE TITLE
API Keys in Clear Text

### ISSUE THREAD

**Issue by JohnBehnke** [abespodcast/abespodcast.github.io#3]
https://github.com/abespodcast/abespodcast.github.io/blob/0abc99339f34b69c6a3afe9f1094b30a7a0880cb/Sources/AbesPodcast/Theme%2BAbes.swift#L248

**Comment by eralpkaraduman** [comment]
Thank you for pointing this out but this key was created by firebase analytics integration, without permission to do anything else than recording analytics, therefore safe to have here.
